worker_num: 3
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomCrop: {}
  - RandomFlip: {prob: 0.5}
  - RandomDistort: {}
  batch_transforms:
  - BatchRandomResize: {target_size: [576, 608, 640, 672, 704], random_size: True, random_interp: True, keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.412,0.411,0.414], std: [0.252,0.253,0.251]}
  - Permute: {}
  batch_size: 30
  shuffle: true
  drop_last: false
  collate_batch: false


EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [640, 640], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.412,0.411,0.414], std: [0.252,0.253,0.251]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 11
  shuffle: false


TestReader:
  inputs_def:
    image_shape: [1, 3, 640, 640]
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [640, 640], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.412,0.411,0.414], std: [0.252,0.253,0.251]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
