metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir:
    anno_path: COCO_train_annos.json
    dataset_dir: data/dataset/train
    data_fields: ['image', 'gt_bbox', 'gt_class']

EvalDataset:
  !COCODataSet
    image_dir:
    anno_path: COCO_val_annos.json
    dataset_dir: data/dataset/val

TestDataset:
  !ImageFolder
    image_dir: data/test
    anno_path: COCO_val_annos.json
    dataset_dir: data/dataset/val